spring:
  mvc:
    dispatch-options-request: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/oreshare
    username: postgres
    password: postgres
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        default_schema: public
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/database/db.changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
server:
  port: 8081
o-reshare:
  files:
    path: /Users/andrei/Desktop/o-reshare